/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * NLW Connect
 * OpenAPI spec version: 0.0.1
 */
export type PostSubscriptionsBody = {
  name: string
  email: string
  /** @nullable */
  referrer?: string | null
}

export type PostSubscriptions201 = {
  subscriberId: string
}

/**
 * @nullable
 */
export type GetInvitesSubscriberId302 =
  | (typeof GetInvitesSubscriberId302)[keyof typeof GetInvitesSubscriberId302]
  | null

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInvitesSubscriberId302 = {
  null: 'null',
} as const

export type GetSubscribersSubscriberIdInviteClicks200 = {
  count: number
}

export type GetSubscribersSubscriberIdInvitesCount200 = {
  count: number
}

export type GetSubscribersSubscriberIdRankingPosition200 = {
  /** @nullable */
  position: number | null
}

export type GetRanking200Item = {
  id: string
  name: string
  score: number
}

/**
 * @summary Subscribe to event
 */
export const getPostSubscriptionsUrl = () => {
  return 'http://127.0.0.1:3333/subscriptions'
}

export const postSubscriptions = async (
  postSubscriptionsBody: PostSubscriptionsBody,
  options?: RequestInit
): Promise<PostSubscriptions201> => {
  const res = await fetch(getPostSubscriptionsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postSubscriptionsBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: PostSubscriptions201 = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Access invite link and redirects user
 */
export const getGetInvitesSubscriberIdUrl = (subscriberId: string) => {
  return `http://127.0.0.1:3333/invites/${subscriberId}`
}

export const getInvitesSubscriberId = async (
  subscriberId: string,
  options?: RequestInit
): Promise<unknown> => {
  const res = await fetch(getGetInvitesSubscriberIdUrl(subscriberId), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: unknown = body ? JSON.parse(body) : {}

  return data
}

/**
 * @summary Get subscriber invite clicks count
 */
export const getGetSubscribersSubscriberIdInviteClicksUrl = (
  subscriberId: string
) => {
  return `http://127.0.0.1:3333/subscribers/${subscriberId}/invite/clicks`
}

export const getSubscribersSubscriberIdInviteClicks = async (
  subscriberId: string,
  options?: RequestInit
): Promise<GetSubscribersSubscriberIdInviteClicks200> => {
  const res = await fetch(
    getGetSubscribersSubscriberIdInviteClicksUrl(subscriberId),
    {
      ...options,
      method: 'GET',
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscribersSubscriberIdInviteClicks200 = body
    ? JSON.parse(body)
    : {}

  return data
}

/**
 * @summary Get subscriber invites count
 */
export const getGetSubscribersSubscriberIdInvitesCountUrl = (
  subscriberId: string
) => {
  return `http://127.0.0.1:3333/subscribers/${subscriberId}/invites/count`
}

export const getSubscribersSubscriberIdInvitesCount = async (
  subscriberId: string,
  options?: RequestInit
): Promise<GetSubscribersSubscriberIdInvitesCount200> => {
  const res = await fetch(
    getGetSubscribersSubscriberIdInvitesCountUrl(subscriberId),
    {
      ...options,
      method: 'GET',
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscribersSubscriberIdInvitesCount200 = body
    ? JSON.parse(body)
    : {}

  return data
}

/**
 * @summary Get subscriber ranking position
 */
export const getGetSubscribersSubscriberIdRankingPositionUrl = (
  subscriberId: string
) => {
  return `http://127.0.0.1:3333/subscribers/${subscriberId}/ranking/position`
}

export const getSubscribersSubscriberIdRankingPosition = async (
  subscriberId: string,
  options?: RequestInit
): Promise<GetSubscribersSubscriberIdRankingPosition200> => {
  const res = await fetch(
    getGetSubscribersSubscriberIdRankingPositionUrl(subscriberId),
    {
      ...options,
      method: 'GET',
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetSubscribersSubscriberIdRankingPosition200 = body
    ? JSON.parse(body)
    : {}

  return data
}

/**
 * @summary Get list ranking
 */
export const getGetRankingUrl = () => {
  return 'http://127.0.0.1:3333/ranking'
}

export const getRanking = async (
  options?: RequestInit
): Promise<GetRanking200Item[]> => {
  const res = await fetch(getGetRankingUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: GetRanking200Item[] = body ? JSON.parse(body) : {}

  return data
}
